elementos/urls.py
from django.urls import path
from . import views

app_name = 'elementos'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('cartas/', views.lista_cartas, name='lista_cartas'),
    path('cartas/<int:id>/', views.detalle_carta, name='detalle_carta'),
]

paginaA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('elementos.urls')),
]

elementos/models.py
from django.db import models
from django.utils import timezone

class Carta(models.Model):
    titulo = models.CharField(max_length=30)
    cuerpo = models.TextField()
    fecha = models.DateField()

    def __str__(self):
        return self.titulo


class Nota(models.Model):
    cuerpo = models.TextField()
    creada = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.cuerpo[:30]

elementos/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from datetime import timedelta
from .models import Carta, Nota


def inicio(request):
    total_cartas = Carta.objects.count()
    notas = Nota.objects.all().order_by('-creada')

    return render(request, 'inicio.html', {
        'total_cartas': total_cartas,
        'notas': notas
    })


def lista_cartas(request):
    cartas = Carta.objects.all().order_by('-fecha')
    return render(request, 'lista_cartas.html', {
        'cartas': cartas
    })


def detalle_carta(request, id):
    carta = get_object_or_404(Carta, id=id)
    return render(request, 'detalle_carta.html', {
        'carta': carta
    })

elementos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buzón de Abi</title>
    <link rel="stylesheet" href="{% static 'elementos/css/styles.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'elementos:inicio' %}">
            📬 Buzón de Abi
        </a>

        <div class="ms-auto">
            <a class="nav-link text-white" href="{% url 'elementos:lista_cartas' %}">
                Cartas
            </a>
        </div>
    </div>
</nav>

<main class="container py-5">
    {% block content %}{% endblock %}
</main>
<script>
document.addEventListener("DOMContentLoaded", function () {
    const btn = document.getElementById("btnSanValentin");
    if (btn) {
        btn.addEventListener("click", function () {
            document.getElementById("modalSan").style.display = "block";
        });
    }
});

function cerrarSan() {
    document.getElementById("modalSan").style.display = "none";
}
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
{% include "san_valentin_modal.html" %}

</body>
</html>

elementos/templates/cartas.html
{% extends "base.html" %}

{% block content %}

<h2 class="mb-4">📨 Cartas</h2>

<div class="list-group">

    {% for carta in cartas %}
        <a href="#carta{{ carta.id }}"
           class="list-group-item list-group-item-action"
           onclick="mostrarCarta('{{ carta.id }}',
                                  '{{ carta.titulo|escapejs }}',
                                  '{{ carta.cuerpo|escapejs }}',
                                  '{{ carta.fecha }}')">

            <strong>{{ carta.titulo }}</strong><br>
            <small class="text-muted">{{ carta.fecha }}</small>
        </a>
    {% empty %}
        <p>No hay cartas.</p>
    {% endfor %}

</div>

<hr class="my-5">

<div id="detalle-carta" style="display:none;">
    <h3 id="detalle-titulo"></h3>
    <p class="text-muted" id="detalle-fecha"></p>
    <p id="detalle-cuerpo" class="mt-4"></p>
</div>

{% endblock %}

elementos/templates/detalle_carta.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'elementos/css/styles.css' %}">

<a href="{% url 'elementos:lista_cartas' %}"
   class="btn btn-sm btn-outline-secondary mb-4">
    ← Volver
</a>

<div class="carta-real">
    <h2>💌 {{ carta.titulo }}</h2>

    <div class="fecha">
        {{ carta.fecha }}
    </div>

    <p style="white-space: pre-line;">
    {{ carta.cuerpo }}
</p>
</div>

{% endblock %}

elementos/templates/inicio.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="/elementos/static/css/style.css">
<div class="text-center mb-4">
    <h2>📬 Cartas</h2>
    <h4 class="text-muted">{{ total_cartas }} cartas guardadas</h4>

    <a href="{% url 'elementos:lista_cartas' %}" class="btn btn-secondary mt-3">
        Ver cartas
    </a>
</div>

<hr class="my-5">

<h4>📝 Notitas de Efra para Abi</h4>

<div class="d-flex gap-3 flex-wrap">
    {% for nota in notas %}
        <div class="nota">
            <p>{{ nota.cuerpo }}</p>
            <small>
                {{ nota.creada|date:"H:i d/m" }}
            </small>
        </div>
    {% empty %}
        <p>No hay notas.</p>
    {% endfor %}
</div>

<div class="text-center mt-4">
    <button id="btnSanValentin" class="btn-san-valentin">
        💌 Tengo algo para ti
    </button>
</div>




{% endblock %}

elementos/templates/lista_cartas.html
{% extends "base.html" %}

{% block content %}

<h2 class="mb-4">📜 Cartas de Efra</h2>

<a href="{% url 'elementos:inicio' %}" class="btn btn-sm btn-outline-secondary mb-3">
    ← Volver
</a>

<div class="list-group">
    {% for carta in cartas %}
        <a href="{% url 'elementos:detalle_carta' carta.id %}"
           class="list-group-item list-group-item-action carta">
            <strong>{{ carta.titulo }}</strong><br>
            <small class="text-muted">{{ carta.fecha }}</small>
        </a>
    {% empty %}
        <p>No hay cartas.</p>
    {% endfor %}
</div>

{% endblock %}

elementos/templates/notas.html
{% extends "base.html" %}

{% block content %}

<h2 class="mb-4"></h2>

<div class="list-group">

    {% for carta in cartas %}
        <a href="#carta{{ carta.id }}"
           class="list-group-item list-group-item-action"
           onclick="mostrarCarta('{{ carta.id }}',
                                  '{{ carta.titulo|escapejs }}',
                                  '{{ carta.cuerpo|escapejs }}',
                                  '{{ carta.fecha }}')">

            <strong>{{ carta.titulo }}</strong><br>
            <small class="text-muted">{{ carta.fecha }}</small>
        </a>
    {% empty %}
        <p>No hay cartas.</p>
    {% endfor %}

</div>

<hr class="my-5">

<div id="detalle-carta" style="display:none;">
    <h3 id="detalle-titulo"></h3>
    <p class="text-muted" id="detalle-fecha"></p>
    <p id="detalle-cuerpo" class="mt-4"></p>
</div>

{% endblock %}

elementos/templates/san_valentin_modal.html
<div id="modalSan" class="modal-san">
    <div class="modal-contenido">
        <h2>💘 Tengo que preguntarte algo...</h2>

        <p style="font-size: 20px;">
            ¿Quieres ser mi San Valentín?
        </p>

        <a
          href="https://wa.me/5216624006571?text=Sí%20quiero%20ser%20tu%20San%20Valentín%20💖"
          target="_blank"
          class="btn-san-valentin"
        >
            Responder💚
        </a>

        <br><br>

        <button onclick="cerrarSan()"
            style="background:none; border:none; color:#777;">
            Cerrar
        </button>
    </div>
</div>